import {
  Award,
  Users,
  ArrowRight,
  FolderSync,
  Zap,
} from 'lucide-react';
import { Section } from './ui/Section';
import { SectionHeader } from './ui/SectionHeader';
import { Reveal, RevealGroup } from './ui/Reveal';
import { Card } from './ui/Card';

interface ProfessionalNetworkSectionProps {
  onOpenChecker: () => void;
}

export function ProfessionalNetworkSection({
  onOpenChecker,
}: ProfessionalNetworkSectionProps) {
  const benefits = [
    {
      title: 'Automated Client Document Collection',
      desc: 'Stop chasing clients on personal WhatsApp for missing purchase invoices or bank statements. Our bot collects, re-names, and organizes files automatically.',
      icon: FolderSync,
    },
    {
      title: 'Pre-Reconciled GSTR-2B Workpapers',
      desc: 'Get clean, mathematically verified 2B vs purchase ledgers and draft form computations so your billable time is spent on strategy, not manual VLOOKUPs.',
      icon: Zap,
    },
    {
      title: 'Maintain Your Client Relationships',
      desc: 'We are not an aggregator trying to steal your clients. Bring your existing MSME clients onto the platform to give them modern technology under your guidance.',
      icon: Users,
    },
    {
      title: 'Monetize Network Filings & Certifications',
      desc: 'Accept statutory audit, certification, or representation assignments generated by growing businesses on the ComplianceEasily network in your city.',
      icon: Award,
    },
  ];

  return (
    <Section tone="cream" withGrid id="for-professionals">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        <Reveal className="lg:col-span-6 space-y-6">
          <SectionHeader
            align="left"
            eyebrow={
              <>
                <Award className="w-3.5 h-3.5" />
                <span className="text-[10px] font-bold tracking-widest uppercase font-mono">
                  FOR PRACTICING CAS, CSS &amp; ADVOCATES
                </span>
              </>
            }
            title={
              <>
                Manage more clients. <br />
                <span className="text-[#B89E6B]">Chase fewer deadlines.</span>
              </>
            }
            description="Work with ComplianceEasily or invite your own clients onto the platform. We handle the intake, the document follow-ups, and the first-pass data extractions, letting you focus on advisory, certification, and high-value compliance strategy."
          />

          <div className="pt-2 flex flex-col sm:flex-row items-stretch sm:items-center gap-3 font-mono">
            <button
              type="button"
              onClick={onOpenChecker}
              className="btn-primary inline-flex items-center justify-center space-x-2 font-bold text-xs uppercase tracking-wider"
            >
              <span>Join the Professional Network</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
            <button
              type="button"
              onClick={onOpenChecker}
              className="inline-flex items-center justify-center font-bold text-xs uppercase tracking-wider px-5 py-3 rounded-lg border border-[#D5D0C6] bg-[#FFFFFF] text-[#0E1217] hover:bg-[#F4F2EE] hover:border-[#B89E6B] transition-colors"
            >
              Invite My Existing Clients
            </button>
          </div>

          <div className="text-xs font-mono text-[#6B7580] pt-1">
            ✓ For ICAI practicing members &bull; ICSI practicing members &bull; Bar Council advocates
          </div>
        </Reveal>

        <RevealGroup className="lg:col-span-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
          {benefits.map((b) => {
            const Icon = b.icon;
            return (
              <Card key={b.title} className="p-5 space-y-2.5">
                <div className="w-9 h-9 rounded-lg bg-[#EBE8E2] border border-[#D5D0C6] flex items-center justify-center text-[#B89E6B]">
                  <Icon className="w-4 h-4" />
                </div>
                <h3 className="text-xs font-bold text-[#0E1217] tracking-wider uppercase font-mono">
                  {b.title}
                </h3>
                <p className="text-xs text-[#5C6570] leading-relaxed">{b.desc}</p>
              </Card>
            );
          })}
        </RevealGroup>
      </div>
    </Section>
  );
}
