# Each added record has a bounded source assertion. Partial research is not full legal verification.
EXTRA_SOURCES = [
 ('CSR','https://csrxchange.gov.in/Frontend/faq','MCA CSR FAQs','Section 135 thresholds and CSR framework'),
 ('LLP3','https://www.mca.gov.in/content/dam/mca/mca-forms-instruction-kit/InstructionKit_LLPForm%20No%203.pdf','LLP Form 3 instruction kit','Agreement filing and linked partner-change forms'),
 ('EPR_PLASTIC','https://eprplastic.cpcb.gov.in/','CPCB plastic EPR portal','PIBO and processor registration; common EPR SSO'),
 ('EPR_BATTERY','https://eprbattery.cpcb.gov.in/','CPCB battery EPR portal','Producer, recycler and refurbisher registration'),
 ('EPR_EWASTE','https://www.eprewaste.cpcb.gov.in/','CPCB e-waste portal','Registration and EPR targets for covered equipment'),
 ('EPR_TYRE','https://eprtyres.cpcb.gov.in/assets/Guidance_Document_for_Generation_and_Transfer_of_EPR_Certificate_for_wastetyremanagement.pdf','CPCB waste tyre certificate guidance','Producer obligations and recycler supporting data'),
 ('EPR_OIL','https://eprusedoil.cpcb.gov.in/page/1','CPCB used oil EPR portal','2023 used-oil EPR framework'),
 ('EPR_CD','https://cdwm.cpcb.gov.in/about-system','CPCB construction and demolition waste system','Registration, EPR and waste-utilisation platform'),
 ('FSSAI_RETURN','https://www.youtube.com/watch?v=wZsnpaihOcU','FSSAI official annual-return announcement 27 April 2026','FY 2025-26 return due 31 May 2026; online only'),
 ('FOSCOS','https://foscos.fssai.gov.in/','FoSCoS announcements and services','Annual return, modification and recall services'),
 ('ESANCHIT','https://www.icegate.gov.in/services/e-sanchit','ICEGATE e-Sanchit','Electronic supporting-document submission'),
 ('ICEGATE_MANUAL','https://www.icegate.gov.in/sites/default/files/2024-05/User%20Manual%20Main%20Website_v1.02_0.pdf','ICEGATE website manual','Customs online services and supporting documents'),
 ('CGWA','https://cgwb.gov.in/en/ground-water-regulation','CGWB groundwater regulation','CGWA and state groundwater jurisdiction'),
 ('PSARA','https://www.mha.gov.in/sites/default/files/2023-01/FAQ_10012023.pdf','MHA PSARA FAQs','State/UT controlling authority and online licence portal'),
 ('RERA_KL','https://rera.kerala.gov.in/storage/documents/195.pdf','Kerala RERA registration clarification','Kerala interpretation of area/apartment registration tests'),
 ('TRANSPORT','https://parivahan.gov.in/content/about-permit','Parivahan permits','Transport-vehicle permit categories'),
 ('FITNESS','https://parivahan.gov.in/sites/default/files/FAQDOCS/VAHANSERVICES/FitnessCertificate/stepBystep.pdf','Parivahan fitness application guide','Online application and fitness process'),
 ('DOT_ETA','https://eservices.dot.gov.in/taxonomy/term/307','DoT equipment type approval','Self-declaration route for qualifying finished products'),
 ('DOT_AUTH','https://eservices.dot.gov.in/authorisation-portal','DoT authorisation portal','Telecom/radio authorisation discovery'),
 ('DGMS','https://www.dgms.gov.in/','DGMS services','Mine-safety authority and notices'),
 ('CROP','https://www.cgg.gov.in/it_project/comprehensive-registration-of-pesticides-crop/','Government CROP/PQMS project description','Pesticide registration and plant quarantine systems'),
 ('PQMS','https://pqms.cgg.gov.in/pqms-angular/login','Plant Quarantine Management System','Plant quarantine online system')]
for sid,url,title,supports in EXTRA_SOURCES: source(sid,url,title,supports)

companies=['private_company','public_company','section8']
ngos=['trust','society','section8']
def extra(code,name,dept,law,applies,deadline,triggers,sid,docs='',**kw):
    url=kw.pop('website',next(s['url'] for s in TABLES['sources'] if s['source_id']==sid))
    finding=kw.pop('finding','Source establishes the described regulatory framework or service; unresolved deadlines, applicability exceptions and physical steps remain subject to review.')
    return new_rule(code,name,dept,law,applies,deadline,triggers,documents=docs,sources=[(sid,'framework_or_procedure',finding)],website=url,**kw)

extra('N001','CSR applicability, governance and spending','MCA','Companies Act 2013 section 135; CSR Policy Rules','Companies meeting any section 135 financial test in the immediately preceding FY; evaluate statutory exclusions and committee exceptions.','Annual assessment; spending and unspent transfers have distinct statutory dates.',['date','turnover'],'CSR','Financial statements; section 198 profit computation; CSR policy; project and spending records',entities=companies,turnover='Net worth >= INR 500 crore OR turnover >= INR 1000 crore OR net profit >= INR 5 crore; distinct statutory definitions',frequency='annual',website='https://www.mca.gov.in/',expression={'any':[term('net_worth_inr','gte',5000000000),term('company_turnover_inr','gte',10000000000),term('net_profit_inr','gte',50000000)]},finding='Section 135 has three alternative financial tests; company eligibility and spending calculation are separate.')
extra('N002','TReDS mandatory onboarding','MSME','MSME notification implementing revised TReDS onboarding threshold','Companies with turnover exceeding INR 250 crore and all CPSEs.','Original onboarding deadline 31 March 2025; test new entrants and subsequent directions.',['turnover','law_change'],'TREDS','PAN; CIN; authorised signatory; financial turnover and bank particulars',entities=companies,turnover='Company turnover > INR 2500000000; CPSE alternative irrespective of turnover',website='https://www.msme.gov.in/',expression={'any':[term('company_turnover_inr','gt',2500000000),term('is_cpse','eq',True)]},notes='Onboarding does not compel every invoice to be financed. Select an RBI-authorised TReDS operator; ministry URL is guidance.')
extra('N003','LLP agreement filing / changes — Form 3','LLP','LLP Act 2008; LLP Rules 2009','LLPs entering or changing their agreement.','Use current Form 3 instruction kit and event date; linked Form 4/5 where applicable.',['transaction','director_partner'],'LLP3','Executed agreement or amendment; relevant partner approvals; DSC; applicable state stamp duty',entities=['llp'],mode='online',website='https://www.mca.gov.in/',testing='conditional',notes='Electronic filing does not establish that agreement execution or stamping is fully digital.')
extra('N004','LLP partner appointment / cessation / particulars — Form 4','LLP','LLP Act 2008; LLP Rules 2009','LLP partner or designated-partner change; examine linked agreement amendment.','Event-based; confirm current Form 4 instruction kit before calculating a deadline.',['director_partner'],'LLP3','Consent; appointment/cessation evidence; identity particulars; DSC',entities=['llp'],mode='online',website='https://www.mca.gov.in/',finding='Form 3 instruction kit identifies linked partner-change Form 4; detailed Form 4 timeline not verified.')
extra('N005','Company resolutions filing — MGT-14','MCA','Companies Act 2013 section 117','Specified resolutions and agreements; private-company exemptions must be checked.','Ordinarily 30 days from applicable resolution/agreement; verify class exemption.',['transaction','director_partner'],'MCA_ACT','Resolution; explanatory statement where required; altered constitutional documents if relevant; DSC',entities=companies,mode='online',website='https://www.mca.gov.in/',finding='Section 117 establishes filing for specified resolutions and agreements.')
extra('N006','Beneficial ownership declarations and reporting','MCA','Companies Act 2013 sections 89 and 90; related rules','Registered/beneficial owners and companies where beneficial ownership differs or significant beneficial ownership tests apply.','Declaration and company filing clocks differ; verify current rules and event dates.',['transaction','director_partner'],'MCA_ACT','Ownership chain; beneficial-owner declaration; shareholding and control records',entities=companies,website='https://www.mca.gov.in/',notes='MGT-6 and BEN-2 are different returns; this framework requires form-specific subrules before activation.',finding='Sections 89/90 establish distinct beneficial-ownership obligations; detailed thresholds not independently verified.')
extra('N007','FCRA annual return — FC-4','NGO','Foreign Contribution (Regulation) Act 2010 and Rules','Organisations subject to FCRA annual reporting; examine nil-return and certificate/document exemptions.','Within nine months after FY close; ordinary 31 December for March year end, subject to extensions.',['date'],'FCRA','FCRA registration/prior permission; designated bank statements; annual accounts and audit certificates as applicable',entities=ngos,mode='online',frequency='annual',website='https://fcraonline.gov.in/',finding='FCRA FAQ documents FC-4 annual filing and nine-month window.')
# Separate the inherited combined registration/annual-return record.
next(c for c in TABLES['compliances'] if c['compliance_id']=='C045')['name']='FCRA registration / prior permission before foreign contribution'
next(r for r in TABLES['rule_versions'] if r['rule_id']=='C045-V1').update(deadline_text='Before accepting foreign contribution where registration/prior permission is required; annual FC-4 is N007.',frequency='event_based')
extra('N008','Donation reporting and donor certificate — 10BD/10BE, new 113/114','INCOME_TAX','Period-appropriate Income-tax Act and Rules','Approved institutions subject to donation reporting; select old/new law by reporting period.','Resolve the period-specific due date and transition before scheduling.',['date','transaction'],'IT_FORMS','Donor identification; donation date, amount and mode; approval particulars; certificate records',entities=ngos,frequency='annual',mode='online',website='https://www.incometax.gov.in/',finding='Official directory maps old forms 10BD/10BE to new forms 113/114.')
extra('N009','FSSAI annual return — applicable manufacturers and importers','FSSAI','FSS licensing regulations; FoSCoS annual-return directions','Licensed manufacturers including repackers/relabellers, manufacturer-exporters and importers; not every restaurant or retailer.','FY 2025-26 announced deadline: 31 May 2026. Check extensions and subsequent-year notices.',['date','industry'],'FSSAI_RETURN','Licence particulars; production/import quantities; product and sales data',mode='online',physical='not_required',visit='not_required',frequency='annual',tax_period='FY 2025-26',website='https://foscos.fssai.gov.in/',finding='Official FSSAI announcement identifies filers, 31 May 2026 deadline and excludes physical/email submission.')
extra('N010','FSSAI modification after business / product / premises changes','FSSAI','FSS licensing and registration regulations','Food businesses changing particulars relevant to their registration/licence.','Determine prior-approval requirement for the specific change.',['location','industry','transaction'],'FOSCOS','Existing certificate; changed business/product details; supporting premises or entity documents',mode='online',inspection='conditional',website='https://foscos.fssai.gov.in/',finding='FoSCoS provides modification and migration services; current KoB determines category.')
extra('N011','FSSAI food recall and traceability response','FSSAI','FSS food recall framework and applicable licence conditions','Affected food businesses when food requires recall or regulator directs action.','Incident/order-specific; do not substitute a routine annual deadline.',['notice','transaction'],'FOSCOS','Product and batch records; distribution traceability; recall action and effectiveness records',mode='online',website='https://foscos.fssai.gov.in/',finding='FoSCoS announces food-recall functionality; incident deadline requires applicable recall provision.')

for code,name,sid,law,who,docs in [
 ('N012','Plastic packaging EPR registration','EPR_PLASTIC','Plastic Waste Management Rules and EPR guidelines','Covered producers, importers, brand owners and plastic-waste processors; exemptions/classification require checking.','Entity/PAN/GST details; packaging category and quantity; process details; applicable consent'),
 ('N013','Battery producer / recycler / refurbisher registration','EPR_BATTERY','Battery Waste Management Rules 2022 as amended','Battery producers, recyclers and refurbishers within the rule definitions.','Entity and product details; battery chemistry/quantities; recycling facility and consent records'),
 ('N014','E-waste registration and recycling targets','EPR_EWASTE','E-Waste Management Rules 2022 as amended','Covered electrical/electronic equipment actors; confirm schedule, role and exemptions.','Scheduled equipment category; quantity placed on market; entity and recycler records'),
 ('N015','Waste tyre EPR fulfilment and certificates','EPR_TYRE','Hazardous and Other Wastes Rules; tyre EPR amendments','Covered tyre producers/importers and registered recyclers.','Quantity and invoices; bill of lading where relevant; recycling output and certificate records'),
 ('N016','Used-oil EPR registration and obligations','EPR_OIL','Hazardous and Other Wastes Second Amendment Rules 2023','Covered base/lubrication oil producers/importers and used-oil actors; verify definitions.','Oil category and quantities; entity particulars; relevant processing/consent records'),
 ('N017','Construction and demolition waste registration / EPR','EPR_CD','Applicable construction and demolition waste rules','Covered producers, recyclers and other stakeholders; identify effective rules and project thresholds.','Project and waste quantities; recycler particulars; utilisation and certificate records')]:
    extra(code,name,'WASTE',law,who,'Registration and period-specific targets/returns; validate current schedule and extensions.',['industry','date','transaction'],sid,docs,mode='online',inspection='conditional',notes='Common CPCB EPR SSO: https://epr.cpcb.gov.in/. Online registration is not proof of no facility inspection; quantitative targets remain unresolved.')

extra('N018','Prior environmental clearance','POLLUTION','EIA Notification and amendments','Projects/expansions listed in applicable EIA schedule; assess capacity, location and category.','Obtain required prior clearance before prohibited project activity.',['industry','location','transaction'],'PARIVESH','Project report; site/location maps; prescribed application; environmental studies as required',mode='online',inspection='conditional',testing='conditional',website='https://parivesh.nic.in/',finding='Official clearance forms identify EC applications; individual schedule and procedure require project review.')
extra('N019','Forest diversion approval','POLLUTION','Applicable forest conservation legislation and rules','Use/diversion of covered forest land for non-forest purpose.','Prior approval before covered diversion; stage and conditions depend on proposal.',['location','transaction'],'PARIVESH','Land records; maps; diversion proposal; compensatory afforestation information',mode='online',inspection='conditional',website='https://parivesh.nic.in/',finding='Official forms identify forest clearance as a separate approval.')
extra('N020','CRZ / wildlife clearance assessment','POLLUTION','Applicable coastal-zone and wildlife legislation','Projects in regulated coastal or protected/wildlife-sensitive locations.','Prior project approval where required; exact authority depends on location.',['location','industry'],'PARIVESH','Location and boundary maps; project details; studies and clearance records',mode='online',inspection='conditional',website='https://parivesh.nic.in/',finding='Official clearance inventory distinguishes CRZ and wildlife routes; subrules required.')
extra('N021','Groundwater abstraction NOC','POLLUTION','CGWA guidelines / applicable state groundwater legislation','Industrial, infrastructure or other covered groundwater abstraction; check state jurisdiction and exemptions.','Before covered abstraction; certificate-specific renewals and reporting.',['industry','location','licence'],'CGWA','Water requirement and source; borewell/site details; water balance; applicable studies',scope='central_or_state',website='https://cgwb.gov.in/en/ground-water-regulation',inspection='conditional',notes='CGWA is not the licensing authority for every state; do not use one universal national application.')
extra('N022','Customs import declaration and supporting documents','CUSTOMS','Customs Act and applicable import regulations','Importers of goods subject to customs entry and commodity-specific controls.','Consignment/event-specific bill-of-entry and duty rules.',['transaction','industry'],'ESANCHIT','Commercial invoice; packing list; transport document; origin and product permissions as applicable',mode='online',inspection='conditional',testing='conditional',website='https://www.icegate.gov.in/',finding='e-Sanchit supports electronic documents; it does not remove goods examination or agency testing.')
extra('N023','Customs export declaration and supporting documents','CUSTOMS','Customs Act and export regulations','Exporters of goods; special schemes and restricted products need additional controls.','Shipment-specific declaration and clearance.',['transaction','industry'],'ICEGATE_MANUAL','Invoice; packing list; shipping and scheme particulars; commodity permissions',mode='online',inspection='conditional',website='https://www.icegate.gov.in/',finding='ICEGATE provides customs electronic services; complete consignment rules not verified.')
extra('N024','FDI share issue reporting — FC-GPR','FEMA','FEMA and current foreign-investment reporting directions','Indian company issuing capital instruments covered by FDI reporting.','Use current RBI reporting direction and actual issue date; do not rely on incorporation date alone.',['transaction'],'RBI_FIRMS','Issue/allotment details; foreign remittance and KYC; valuation; professional certifications as applicable',entities=companies,mode='online',website='https://firms.rbi.org.in/',finding='FIRMS lists FC-GPR in Single Master Form; transaction-specific deadlines not independently verified.')
extra('N025','Resident / non-resident transfer reporting — FC-TRS','FEMA','FEMA and current foreign-investment reporting directions','Transfers falling within FC-TRS reporting; determine responsible resident party and exemptions.','Event-specific receipt/remittance or transfer clock under current RBI direction.',['transaction'],'RBI_FIRMS','Transfer agreement; consideration and valuation; buyer/seller residency; bank and KYC records',mode='online',website='https://firms.rbi.org.in/',finding='FIRMS lists FC-TRS; not every transfer has the same reporting obligation.')
extra('N026','Foreign investment in LLP — LLP-I / LLP-II','FEMA','FEMA foreign-investment rules and reporting directions','Foreign capital contribution/profit-share transactions in eligible LLPs.','Select contribution or transfer event and current reporting period.',['transaction','director_partner'],'RBI_FIRMS','LLP agreement; valuation; remittance/KYC; contribution or transfer records',entities=['llp'],mode='online',website='https://firms.rbi.org.in/',finding='FIRMS includes LLP-I and LLP-II reporting.')
extra('N027','Convertible-note foreign-investment reporting — CN','FEMA','FEMA applicable startup convertible-note conditions','Eligible convertible-note issue/transfer involving non-residents; verify startup and amount conditions.','Transaction-specific filing under current direction.',['transaction'],'RBI_FIRMS','Startup eligibility; note agreement; remittance; holder and transfer details',entities=['private_company'],mode='online',website='https://firms.rbi.org.in/',finding='FIRMS includes CN in Single Master Form; eligibility thresholds not checked.')
extra('N028','Packaged-commodity manufacturer / packer / importer registration','LEGAL_METROLOGY','Legal Metrology (Packaged Commodities) Rules, Rule 27','Persons covered as manufacturer, packer or importer of packaged commodities.','Within 90 days of commencing relevant activity, subject to current rule and authority.',['industry','transaction'],'LM_FAQ','Entity and premises particulars; product/packing details; authorisation and fee',scope='central_or_state',finding='Official FAQ specifies Rule 27 registration and ninety-day period.')
extra('N029','Packaged-commodity label and online declarations','LEGAL_METROLOGY','Legal Metrology (Packaged Commodities) Rules','Covered retail packages and relevant e-commerce listings; check product exemptions.','Before relevant sale/offer; update when product or declared particulars change.',['industry','transaction'],'LM','Label artwork; manufacturer/packer/importer particulars; quantity/MRP and consumer-care records',kind='ongoing_duty',finding='Consumer Affairs overview identifies packaged-commodity declaration controls.')
extra('N030','Weighing / measuring instrument model approval and verification','LEGAL_METROLOGY','Legal Metrology Act and applicable rules','Manufacture/import or trade use of covered weighing/measuring instruments.','Model approval and periodic stamping/verification are different events; state intervals apply.',['industry','licence'],'LM','Model specifications; test reports where required; instrument and previous verification certificate',scope='central_or_state',inspection='conditional',testing='conditional',notes='Instrument examination/testing can require physical activity even if booking/payment is online.')
extra('N031','BIS certification for QCO-covered products','BIS','BIS Act; applicable product Quality Control Order','Manufacturers/importers of products with an effective compulsory QCO; verify product, standard, exemptions and commencement.','Certification before regulated manufacture/import/sale; scheme-specific renewal or surveillance.',['industry','law_change','licence'],'BIS','Applicable IS standard; product and factory data; test reports and quality controls',inspection='conditional',testing='conditional',notes='Products outside compulsory orders may have voluntary certification; do not make BIS universal.')
extra('N032','BIS certification testing / surveillance duties','BIS','Applicable BIS certification scheme and licence conditions','BIS licensees where the applicable scheme prescribes tests or factory surveillance.','Use scheme/licence testing plan and surveillance events.',['date','licence'],'BIS_FAQ','Test and production records; licence; quality-control records; samples as required',inspection='conditional',testing='conditional',kind='ongoing_duty')
extra('N033','Drug import / manufacture / sale permission assessment','DRUGS_HEALTH','Drugs and Cosmetics Act and applicable rules','Drug activities; central/state licensing allocation differs by activity and product.','Prior applicable licence; certificate-specific retention/renewal duties.',['industry','location','licence'],'CDSCO','Product and premises dossier; technical staff qualifications; test/manufacturing records as relevant',scope='central_or_state',mode='online',inspection='conditional',testing='conditional',notes='CDSCO SUGAM covers specified central applications; state sale/manufacture licensing must be separately resolved.')
extra('N034','Medical-device licensing by risk class and activity','DRUGS_HEALTH','Medical Devices Rules 2017 as amended','Manufacturers/importers/sellers of regulated devices; distinguish risk classes and exemptions.','Before covered activity; current retention fee and licence conditions.',['industry','licence'],'MEDDEV','Device classification; technical dossier; quality-system and facility evidence',scope='central_or_state',mode='online',inspection='conditional',testing='conditional')
extra('N035','Cosmetics import registration','DRUGS_HEALTH','Cosmetics Rules 2020 as amended','Imports of cosmetics covered by registration rules.','Before import; registration and retention obligations as applicable.',['industry','licence'],'COSMETICS','Manufacturer authorisation; product, label and ingredient particulars; certificates as required',mode='online',inspection='conditional',testing='conditional')
extra('N036','Petroleum storage / installation licence','ENERGY_PESO','Petroleum Rules 2002 as amended','Storage, transport or installation falling within licensed class/quantity; exemptions require exact facts.','Prior approval/licence and certificate-specific renewal.',['industry','location','licence'],'PESO','Site/layout plans; storage class/capacity; safety and competent-person records; district NOC where required',mode='online',inspection='conditional',testing='conditional',website='https://www.peso.gov.in/',notes='PESO FAQ routes applications via NSWS/PESO; physical site examination and certificates depend on licence class.')
extra('N037','CERT-In specified cyber-incident reporting','DATA_CYBER','IT Act section 70B; CERT-In directions 28 April 2022','Service providers, intermediaries, data centres, bodies corporate and government organisations within directions.','Specified incidents: within six hours of noticing or being brought to notice.',['transaction','notice'],'CERT','Incident time/type; affected systems; available indicators; response contact and subsequent details',kind='incident_duty',finding='Directions prescribe six-hour reporting for specified incidents, not every ordinary IT error.')
extra('N038','CERT-In ICT log retention / point of contact','DATA_CYBER','CERT-In directions 28 April 2022','Entities within directions; distinguish special customer-record duties by provider class.','Maintain ICT logs for rolling 180 days securely within India; designate contact as directed.',['date','industry'],'CERT','System logs; time synchronisation evidence; designated contact details',kind='ongoing_duty',frequency='continuous',finding='Directions specify 180-day ICT logs and point-of-contact obligations.')
extra('N039','DPDP commencement and applicability assessment','DATA_CYBER','Digital Personal Data Protection Act 2023; Rules 2025 and commencement notifications','Digital personal-data processing within statutory scope, subject to exclusions and phased commencement.','Evaluate each provision on its notified effective date; no blanket current activation of all duties.',['law_change','industry'],'DPDP','Data inventory; processing purposes; notices/consent records where operative; processor arrangements',kind='law_change_review',notes='This is a transition review, not a finding that all DPDP duties are already in force.')
extra('N040','Transport-vehicle permit','TRANSPORT','Motor Vehicles Act and applicable central/state rules','Commercial/transport use requiring relevant goods/passenger permit; exceptions and area limits apply.','Before covered use and before actual permit expiry.',['industry','location','licence'],'TRANSPORT','Vehicle registration; insurance; tax and fitness particulars; route/use details',scope='state_framework',website='https://parivahan.gov.in/',inspection='conditional')
extra('N041','Transport vehicle fitness certificate','TRANSPORT','Motor Vehicles Act and fitness rules','Covered transport vehicles; age/class and current testing-centre rules determine periodicity.','Use actual certificate expiry and applicable testing interval.',['licence'],'FITNESS','Registration; prior fitness; vehicle and application particulars',scope='state_framework',mode='online_with_physical_step',inspection='required',website='https://parivahan.gov.in/',notes='Online application/payment is only part of fitness certification; vehicle testing is a physical step. Applicant personal attendance is a separate question.')
extra('N042','Wireless equipment type approval','TELECOM','Applicable DoT/WPC spectrum and equipment requirements','Qualifying wireless equipment in licence-exempt bands; self-declaration only for eligible finished-product categories.','Before regulated import/use/sale as applicable to product.',['industry','transaction'],'DOT_ETA','RF test report; product specifications; applicant/importer authorisation',mode='online',testing='conditional',website='https://eservices.dot.gov.in/',notes='Do not equate licence-exempt spectrum with equipment-approval exemption.')
extra('N043','Telecom / radio authorisation assessment','TELECOM','Applicable telecommunications authorisation framework','Providing regulated telecom services or possessing/using radio equipment outside relevant exemptions.','Before covered service/activity; check current authorisation category and transition.',['industry','law_change','licence'],'DOT_AUTH','Entity particulars; proposed service/spectrum/equipment details; technical documents',mode='online',website='https://eservices.dot.gov.in/authorisation-portal')
extra('N044','Mine opening / safety notices','AGRI_MINING','Applicable mine-safety law and OSH transition','Mine owners/managers/operators with opening, operational or reportable safety events.','Event-specific notices; verify current DGMS form and deadline.',['industry','transaction','notice'],'DGMS','Mine location and ownership; manager/agent appointments; operational/safety particulars',inspection='conditional',website='https://www.dgms.gov.in/')
extra('N045','Pesticide registration / import permission','AGRI_MINING','Insecticides Act and applicable rules','Covered pesticide manufacture/import products; state sale/manufacture licensing is additional.','Before relevant product manufacture/import; verify product-specific permission.',['industry','transaction'],'CROP','Product chemistry and efficacy/safety dossier; applicant and manufacturer information',mode='online',testing='conditional',notes='Government implementation source establishes CROP system; exact current checklist not independently checked.')
extra('N046','Plant quarantine clearance / phytosanitary certification','AGRI_MINING','Plant Quarantine Order and applicable export/import phytosanitary requirements','Covered plants, plant products and consignments.','Consignment-specific prior permission/inspection/certificate where prescribed.',['industry','transaction'],'PQMS','Commodity and consignment details; origin/destination; phytosanitary and treatment records',mode='online',inspection='conditional',testing='conditional')
extra('N047','Private security agency licence','LABOUR','Private Security Agencies (Regulation) Act and state rules','Business providing private security agency services in the relevant state/UT.','Before operating; licence conditions and renewal depend on certificate/state rules.',['industry','location','licence'],'PSARA','Entity and controller details; antecedent verification; training arrangements; prescribed affidavits',scope='state_framework',mode='online',inspection='conditional',website='https://psara.gov.in/',notes='State controlling authority grants licence; antecedent checks and training arrangements are separate from uploading application.')
extra('N048','RERA project / agent registration framework','RERA','Real Estate (Regulation and Development) Act; state rules and authority orders','Covered projects and agents; evaluate local thresholds, planning area, phases and exclusions.','Prior registration before covered marketing/sale; local renewal/reporting requirements.',['industry','location','transaction','licence'],'RERA_KL','Title and land particulars; approvals/plans; promoter/agent information; project and financial details',scope='state_framework',notes='Source is Kerala-specific; its interpretation is not asserted as a verified rule for every state.',finding='Kerala authority clarifies project-registration thresholds; other jurisdictions require their own evidence.')

# All requested trigger categories exist, including law changes as explicit reassessment events.
extra('N049','Labour-code transition review for each establishment','LABOUR','Four Labour Codes and operative central/state rules, schemes and savings','Establishments affected by revised wages, safety, industrial-relations and social-security provisions.','Reassess from commencement and later applicable rule notifications.',['law_change','employee','location'],'LABOUR_CODES','Establishment classification; worker/wage history; applicable registrations; current employment policies',scope='central_or_state',kind='law_change_review',effective='2025-11-21',notes='A commencement announcement alone does not verify every threshold or state procedural rule.')
